version: "3.8"

services:
  server:
    image: gitea/gitea:latest-rootless
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - VIRTUAL_HOST=gitea.openorg.software
      - LETSENCRYPT_HOST=gitea.openorg.software
      - VIRTUAL_PORT=3000
    env_file:
      - gitea.env
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea  
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2222:2222"
    depends_on:
      - db
    networks:
      - gitea

  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_DB=gitea
    env_file:
      - gitea.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - gitea
      
networks:
  gitea:
    external: false