version: "3.8"
services:

  db:
    image: postgres:11-alpine
    container_name: wiki-js-db
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_USER=wikijs
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - wikijs-db

  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki-js
    restart: unless-stopped
    depends_on:
      - db
    env_file: 
      - .env
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wiki-js-db
      - DB_PORT=5432
      - DB_USER=wikijs
      - DB_NAME=wiki
      - VIRTUAL_HOST=wiki.openorg.software
      - LETSENCRYPT_HOST=wiki.openorg.software
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=3000
    networks:
      - proxy
      - wikijs-db

volumes:
  db-data:
  
networks:
  wikijs-db:
  proxy:
    external: true
