version: '3'

services:
  keycloak-postgres:
      image: postgres:13
      container_name: keycloak-postgres
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
      env_file:
        - .env
      environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
      networks:
        - keycloak
      restart: unless-stopped
  keycloak-server:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak-server
      entrypoint:
        - /opt/keycloak/bin/kc.sh
        - start
        - --auto-build
        - --proxy=edge
      env_file:
        - .env
      restart: unless-stopped
      environment:
        - VIRTUAL_HOST=sso.openorg.software
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=sso.openorg.software
        - KC_DB=postgres
        - KC_DB_URL=jdbc:postgresql://keycloak-postgres:5432/keycloak
        - KC_DB_USERNAME=keycloak
        - KC_HOSTNAME=sso.openorg.software
        - KEYCLOAK_ADMIN=admin
      depends_on:
        - keycloak-postgres
      networks:
        - proxy
        - keycloak

networks:
  proxy:
    external: true
  keycloak:
    external: false
