version: "3.8"

services:

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    image: nextcloud:23-apache
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - "POSTGRES_HOST=db"
      - "POSTGRES_DB=nextcloud"
      - "POSTGRES_USER=nextcloud"
      - "REDIS_HOST=redis"
      - "PHP_UPLOAD_LIMIT=10G"
      - "PHP_MEMORY_LIMIT=1G"
      - "VIRTUAL_HOST=cloud.openorg.software"
      - "LETSENCRYPT_HOST=cloud.openorg.software"
      - "VIRTUAL_PORT=80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - proxy

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - nextcloud

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - proxy

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: unless-stopped
    expose:
      - '5672'
    networks:
      - proxy

  onlyoffice:
    image: onlyoffice/documentserver:6
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - "DB_TYPE=postgres"
      - "DB_HOST=onlyoffice-postgresql"
      - "DB_PORT=5432"
      - "DB_NAME=onlyoffice"
      - "DB_USER=onlyoffice"
      - "AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq"
      - "VIRTUAL_HOST=office.openorg.software"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=office.openorg.software"
      - "JWT_ENABLED=true"
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_logs:/var/log/onlyoffice
      - /var/lib/onlyoffice/documentserver/App_Data/cache/files
      - /var/www/onlyoffice/documentserver-example/public/files
      - /usr/share/fonts
    env_file:
      - .env
    networks:
      - proxy

volumes:
  db:
  nextcloud:
  postgresql_data:
  document_data:
  document_logs:

networks:
  proxy:
    external: true
