version: "3"
services:
  kroki:
    image: yuzutech/kroki
    container_name: kroki
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=kroki.openorg.software
      - LETSENCRYPT_HOST=kroki.openorg.software
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=8000
    networks:
      - kroki
      - appwrite_runtimes
      - proxy

networks:
  kroki:
    external: true
  appwrite_runtimes:
    external: true
  proxy:
    external: true