version: "3.8"
services:
  website:
    image: flashspys/nginx-static
    container_name: website
    volumes:
      - ./static:/static:ro
      - ./nginx/conf:/etc/nginx/conf.d/
    environment:
      - VIRTUAL_HOST=tt.openorg.software
      - LETSENCRYPT_HOST=tt.openorg.software
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=80
    networks:
      - proxy
networks:
  proxy:
    external: true
